#!/usr/bin/env bash
#
# This script will grab all the geocat ancillary data you need and build up
# the usual data/ folder in the current directory.

set -e

mkdir -p data/crtm data/instrument_data data/sfc_data data/plod/lit_end data/navigation

CAL_FILE=geocat_cal_v0_4.tar
NAV_FILE=geocat_nav_v0_2.tar.gz
PFA_FILE=geocat_pfaast_luts_v0_2.tar
SFC_FILE=geocat_sfc_data_v0_2.tar.gz

wget -q ftp://ftp.ssec.wisc.edu/pub/geocat/calibration/${CAL_FILE}
wget -q ftp://ftp.ssec.wisc.edu/pub/geocat/navigation/${NAV_FILE}
wget -q ftp://ftp.ssec.wisc.edu/pub/geocat/pfaast/${PFA_FILE}
wget -q ftp://ftp.ssec.wisc.edu/pub/geocat/surface_data/${SFC_FILE}

tar xf ${CAL_FILE} -C ./data/instrument_data
tar xf ${NAV_FILE} -C ./data/navigation
tar xf ${PFA_FILE} -C ./data/plod/lit_end
tar xf ${SFC_FILE} -C ./data/sfc_data

rm ${CAL_FILE}
rm ${NAV_FILE}
rm ${PFA_FILE}
rm ${SFC_FILE}

cp -r ${CRTM}/coeffs/* data/crtm/.

echo "Geocat ancillary directory ${PWD}/data set up successfully!"
